# External variables:
# Package
#   The package to build and test. Defined in pipeline web ui because multiple pipelines use this YAML with different packages.
#   Example: eventhubs-client
#
trigger:
  - master

variables:
  NodeVersion: '10.x'
  PackageArgument: coalesce('All', $(Package))

jobs:
  - job: 'Build'

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - powershell: |
       Write-Host "transformed: $PackageArgument"
       Write-Host "as-is: $Package"
      displayName: 'Output Some Variables'

